CREATE TEMPORARY EXTERNAL TABLE hw2_test (
    id  INT,
    if1 INT,
    if2 INT,
    if3 INT,
    if4 INT,
    if5 INT,
    if6 INT,
    if7 INT,
    if8 INT,
    if9 INT,
    if10 INT,
    if11 INT,
    if12 INT,
    if13 INT, 
    cf1 VARCHAR,
    cf2 VARCHAR,
    cf3 VARCHAR,
    cf4 VARCHAR,
    cf5 VARCHAR,
    cf6 VARCHAR,
    cf7 VARCHAR,
    cf8 VARCHAR,
    cf9 VARCHAR,
    cf10 VARCHAR,
    cf11 VARCHAR,
    cf12 VARCHAR,
    cf13 VARCHAR,
    cf14 VARCHAR,
    cf15 VARCHAR,
    cf16 VARCHAR,
    cf17 VARCHAR,
    cf18 VARCHAR,
    cf19 VARCHAR,
    cf20 VARCHAR,
    cf21 VARCHAR,
    cf22 VARCHAR,
    cf23 VARCHAR,
    cf24 VARCHAR,
    cf25 VARCHAR,
    cf26 VARCHAR,
    day_number INT)
    ROW FORMAT DELIMITED
    FIELDS TERMINATED BY '\t'
    STORED AS TEXTFILE
    LOCATION /datasets/criteo_test_large_features;
    