CREATE TEMPORARY EXTERNAL TABLE hw2_test (
    id  string,
    if1 string,
    if2 string,
    if3 string,
    if4 string,
    if5 string,
    if6 string,
    if7 string,
    if8 string,
    if9 string,
    if10 string,
    if11 string,
    if12 string,
    if13 string, 
    cf1 string,
    cf2 string,
    cf3 string,
    cf4 string,
    cf5 string,
    cf6 string,
    cf7 string,
    cf8 string,
    cf9 string,
    cf10 string,
    cf11 string,
    cf12 string,
    cf13 string,
    cf14 string,
    cf15 string,
    cf16 string,
    cf17 string,
    cf18 string,
    cf19 string,
    cf20 string,
    cf21 string,
    cf22 string,
    cf23 string,
    cf24 string,
    cf25 string,
    cf26 string,
    day_number string)
    ROW FORMAT DELIMITED
    FIELDS TERMINATED BY '\t'
    STORED AS TEXTFILE
    LOCATION '/datasets/criteo_test_large_features';
    
    